name: Build Images
on: [ push ]
env:
  DOCKER_VERSION_FULL: "0.21.0"
  DOCKER_VERSION_MINOR: "0.21"
  DOCKER_VERSION_MAJOR: "0"
jobs:
  images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build and push zola
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            thibaultmorin/zola:${{ env.DOCKER_VERSION_MAJOR }}
            thibaultmorin/zola:${{ env.DOCKER_VERSION_MINOR }}
            thibaultmorin/zola:${{ env.DOCKER_VERSION_FULL }}
          build-args: |
            version=${{ env.DOCKER_VERSION_FULL }}
            git_sha=${{ github.sha }}
